
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'cj'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  static_incremental_days: 3 # Number of days to scan and reprocess on each run
  cj:
    cta_click_custom_parameters:
      - name: 'click_text'
        value_type: 'string_value'
      - name: 'click_target'
        value_type: 'string_value'
    cta_view_custom_parameters:
      - name: "cta_type"
        value_type: "string_value"
    form_start_custom_parameters:
      - name: 'form_destination'
        value_type: 'string_value'
      - name: 'form_length'
        value_type: 'int_value'
    form_submit_custom_parameters:
      - name: 'form_destination'
        value_type: 'string_value'
      - name: 'form_length'
        value_type: 'int_value'
      - name: 'form_id'
        value_type: 'string_value'
  ga4:
    source_project: "cj-data-warehouse-417316" # Project that contains raw GA4 data
    property_ids: [244396510] # Array of properties to process
    start_date: "20240401" # Earliest date to load
    query_parameter_exclusions: ["gclid","fbclid","_ga", "utm_source", "utm_medium", "utm_campaign"] 
    user_properties:
      - user_property_name: "is_lead"
        value_type: "string_value"
    conversion_events: ['purchase','generate_lead']

models:
  cj:
    marts:
      +schema: analytics
    staging:
      stg_ga4__events:
        +enabled: false 
  ga4:
    marts:
      +schema: analytics
    staging:
      recommended_events:
        stg_ga4__event_add_payment_info:
          +enabled: true 
        stg_ga4__event_begin_checkout:
          +enabled: true 
        stg_ga4__event_generate_lead:
          +enabled: true 
        stg_ga4__event_purchase:
          +enabled: true
        stg_ga4__event_purchase_deduplicated:
          +enabled: true
        stg_ga4__event_view_item:
          +enabled: true 